// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElBadge: typeof import('element-plus/es')['ElBadge']
  const ElLink: typeof import('element-plus/es')['ElLink']
}
export {}
