// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElBadge: typeof import('element-plus/es')['ElBadge']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElLink: typeof import('element-plus/es')['ElLink']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
}
export {}
