// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElLink: typeof import('element-plus/es')['ElLink']
    Header: typeof import('./src/components/header/index.vue')['default']
  }
}

export { }
